on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  deploy_job:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ftp_server }}
          port: '21'
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          sftp_only: true
